# Generated by Django 4.0.3 on 2022-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('first_names', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('client_document_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('client_document_request_id', models.IntegerField()),
                ('storage_location', models.CharField(max_length=200)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocumentRequest',
            fields=[
                ('client_document_request_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('relationship_manager_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('document_type', models.CharField(max_length=20)),
                ('document_format', models.CharField(max_length=20)),
                ('document_request_status', models.CharField(max_length=20)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmailIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientRelationshipManager',
            fields=[
                ('relationship_manager_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipManager',
            fields=[
                ('relationship_manager_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
