# Generated by Django 4.0.3 on 2022-03-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocumentEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('event_type', models.CharField(max_length=50)),
                ('create_ts', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientdocument',
            name='client_document_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clientdocumentrequest',
            name='client_document_request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relationshipmanager',
            name='relationship_manager_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
