# Generated by Django 4.0.3 on 2022-03-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientdocumentevent_alter_client_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocumentDataModel',
            fields=[
                ('client_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_document_request_id', models.IntegerField()),
                ('storage_location', models.CharField(max_length=200)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocumentEventDataModel',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('event_type', models.CharField(max_length=50)),
                ('create_ts', models.DateTimeField(auto_now=True)),
                ('create_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocumentRequestDataModel',
            fields=[
                ('client_document_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship_manager_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('description', models.CharField(default='Client document request', max_length=300)),
                ('accepted_document_formats', models.CharField(default='all', max_length=20)),
                ('request_status', models.CharField(default='pending', max_length=20)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmailIdentityDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRelationshipManagerDataModel',
            fields=[
                ('relationship_manager_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('update_ts', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientDataModel',
        ),
        migrations.RenameModel(
            old_name='RelationshipManager',
            new_name='RelationshipManagerDataModel',
        ),
        migrations.DeleteModel(
            name='ClientDocument',
        ),
        migrations.DeleteModel(
            name='ClientDocumentEvent',
        ),
        migrations.DeleteModel(
            name='ClientDocumentRequest',
        ),
        migrations.DeleteModel(
            name='ClientEmailIdentity',
        ),
        migrations.DeleteModel(
            name='ClientRelationshipManager',
        ),
    ]
