# Generated by Django 4.0.3 on 2022-03-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_relationshipmanageremailidentitydatamodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocumentrequestdatamodel',
            name='encoded_client_document_request_id',
            field=models.CharField(default='hXVljoxCXPKlCuyKjj1UQkEtz3HUZHUw', max_length=32),
        ),
    ]
