# Generated by Django 4.0.3 on 2022-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_clientdocumentrequestdatamodel_encoded_client_document_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocumentrequestdatamodel',
            name='encoded_client_document_request_id',
            field=models.CharField(default='vBTLTcQH1twTvvsSycSV5xIn3LqhNeXd', max_length=32),
        ),
    ]
