# Generated by Django 4.0.3 on 2022-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_clientdocumentrequestdatamodel_encoded_client_document_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocumentdatamodel',
            name='client_document_request_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientdocumentdatamodel',
            name='client_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientdocumentrequestdatamodel',
            name='encoded_client_document_request_id',
            field=models.CharField(default='gMzc7p39pSjDd8b9aWuhI0qpQDlBzRke', max_length=32),
        ),
    ]
